### PR TITLE
Update plg_task_checkin.ini

### PR DESCRIPTION
**Pull request by brianteeman**
see https://developer.joomla.org/en-gb-user-interface-text-guidelines/action-or-description.html for explanation

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks :⁠-⁠)

**Comment by brianteeman** [comment]
No problem. Any reason not to have contributed this to core. It would be a useful addition and more useful than the other tasks

**Comment by zero-24** [comment]
No specific reason. It was requested by Markus so i build it for him and put it on the JED. Would have no problem to contribute it back to the core.

**Comment by zero-24** [comment]
Just reached out to Olivier on MM lets see what he says :)

**Comment by zero-24** [comment]
PR against the core can be found here: https://github.com/joomla/joomla-cms/pull/39323

**Pull request merged**
